image: python:3.8

before_script:
  - python -V
  - pip install --upgrade pip

stages:
  - test
  - style
  - deploy

test:
  stage: test
  services:
    - name: postgres:13.0
      alias: database
  variables:
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: 'postgres'
    POSTGRES_DB: 'test'
    DEBUG: "True"
    TEST_MODE: "True"
  before_script:
    - pip install -r requirements.txt
  script:
    - coverage run -m pytest --disable-warnings
    - coverage report --omit=app/test_app.py -m
    - coverage html --omit=app/test_app.py
    - mkdir public
    - mv htmlcov public/coverage
  artifacts:
    paths:
      - public/coverage
  only:
    - master

pylint:
  stage: style
  before_script:
    - pip install pylint==2.6.0
    - pip install pylint-json2html==0.2.0
    - pip install anybadge==1.7.0
  script:
    - pylint -j 0 app/*.py | tee pylint.txt
    - mkdir public
    - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
    - anybadge --value=$score --file=public/pylint.svg pylint
    - echo "Pylint score was $score"
    - pylint -j 0 app/*.py --output-format=jsonextended > pylint.json
    - pylint-json2html -f jsonextended -o public/pylint.html pylint.json
    - rm pylint.txt pylint.json
  artifacts:
    paths:
      - public/pylint.svg
      - public/pylint.html
  only:
    - master


pages:
  stage: deploy
  script:
  - echo 'Publish pages data'
  artifacts:
    paths:
    - public
  only:
  - master

